In [96]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [97]:
pop=pd.read_csv("data/raw/A2_Pop_per_Sesso_e_Quartiere.csv")

In [98]:
pop.columns

Index(['Quartiere', 'Femmine', 'Maschi'], dtype='object')

In [99]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Quartiere  23 non-null     object
 1   Femmine    23 non-null     int64
 2   Maschi     23 non-null     int64
dtypes: int64(2), object(1)
memory usage: 684.0+ bytes

In [100]:
pop.rename(columns={
    "Quartiere": "neighborhood",
    "Femmine": "female",
    "Maschi": "male"
}, inplace=True)

In [101]:
pop["total_population"] = pop["female"] + pop["male"]

In [102]:
pop["neighborhood_clean"] = (
    pop["neighborhood"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [103]:
pop["statistical_zone_clean"] = (
    pop["neighborhood_clean"]
    .astype(str)
    .str.extract(r"^(\d+)")[0]
    .astype(int)
    .astype(str)
    .str.zfill(2)
)

In [104]:
pop

,neighborhood,female,male,total_population,neighborhood_clean,statistical_zone_clean
0,1 Centro,20840,21404,42244,1 centro,01
1,2 San Salvario,18426,16551,34977,2 san salvario,02
2,3 Crocetta,18334,15675,34009,3 crocetta,03
3,4 San Paolo,17505,15847,33352,4 san paolo,04
4,5 Cenisia,19379,17477,36856,5 cenisia,05
5,6 San Donato,25909,23472,49381,6 san donato,06
6,7 Aurora,20001,19691,39692,7 aurora,07
7,8 Vanchiglia,16165,13770,29935,8 vanchiglia,08
8,9 Nizza millefonti,14662,13100,27762,9 nizza millefonti,09
9,10 Mercati generali,24886,22238,47124,10 mercati generali,10
10,11 Santa Rita,29680,25505,55185,11 santa rita,11
11,12 Mirafiori Nord,22279,19751,42030,12 mirafiori nord,12
12,13 Pozzo Strada,29681,26078,55759,13 pozzo strada,13
13,14 Parella,24915,22270,47185,14 parella,14
14,15 Le Vallette,21059,19658,40717,15 le vallette,15
15,16 Madonna di Campagna,21362,20243,41605,16 madonna di campagna,16
16,17 Borgata Vittoria,21086,19414,40500,17 borgata vittoria,17
17,18 Barriera di Milano,25284,25221,50505,18 barriera di milano,18
18,19 Falchera,13361,12609,25970,19 falchera,19
19,20 Regio Parco,15042,13757,28799,20 regio parco,20
20,21 Madonna del Pilone,7736,6858,14594,21 madonna del pilone,21
21,22 Borgo Po e Cavoretto,10708,9239,19947,22 borgo po e cavoretto,22
22,23 Mirafiori Sud,17810,16378,34188,23 mirafiori sud,23

In [105]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   neighborhood            23 non-null     object
 1   female                  23 non-null     int64
 2   male                    23 non-null     int64
 3   total_population        23 non-null     int64
 4   neighborhood_clean      23 non-null     object
 5   statistical_zone_clean  23 non-null     object
dtypes: int64(3), object(3)
memory usage: 1.2+ KB

In [106]:
pop.describe()

             female          male  total_population
count     23.000000     23.000000         23.000000
mean   19830.869565  18095.913043      37926.782609
std     5530.720307   5098.359646      10581.593405
min     7736.000000   6858.000000      14594.000000
25%    16835.000000  14722.500000      31643.500000
50%    20001.000000  19414.000000      39692.000000
75%    23582.500000  21821.000000      44684.000000
max    29681.000000  26078.000000      55759.000000

cleaning and preprocessing

In [107]:
pop.isna().sum()

neighborhood              0
female                    0
male                      0
total_population          0
neighborhood_clean        0
statistical_zone_clean    0
dtype: int64

In [108]:
pop.dtypes

neighborhood              object
female                     int64
male                       int64
total_population           int64
neighborhood_clean        object
statistical_zone_clean    object
dtype: object

In [109]:
pop.duplicated().sum()

np.int64(0)

In [110]:
(pop[["female", "male", "total_population"]] < 0).any()

female              False
male                False
total_population    False
dtype: bool

In [111]:
pop["neighborhood_clean"].nunique()

23

In [112]:
pop["neighborhood_clean"].value_counts()

neighborhood_clean
1 centro                   1
2 san salvario             1
3 crocetta                 1
4 san paolo                1
5 cenisia                  1
6 san donato               1
7 aurora                   1
8 vanchiglia               1
9 nizza millefonti         1
10 mercati generali        1
11 santa rita              1
12 mirafiori nord          1
13 pozzo strada            1
14 parella                 1
15 le vallette             1
16 madonna di campagna     1
17 borgata vittoria        1
18 barriera di milano      1
19 falchera                1
20 regio parco             1
21 madonna del pilone      1
22 borgo po e cavoretto    1
23 mirafiori sud           1
Name: count, dtype: int64

In [113]:
pop.shape

(23, 6)

In [114]:
pop.columns

Index(['neighborhood', 'female', 'male', 'total_population',
       'neighborhood_clean', 'statistical_zone_clean'],
      dtype='object')

In [115]:
com = pd.read_csv(
    r"C:\Users\reyha\Desktop\torino-retail-intelligence\data\raw\attivita_commerciali.csv",
    sep=';',
    encoding='latin-1')

In [116]:
com

,WKT_GEOM,C_COMP_MERC,INDIRIZZ,CARRAIO,FRONTE,INSEGNA,ANNO_INI,MESE_INI,TIPO_MER,DESC_RIP,...,MQ_TOT_V,TIPO_ADD,NOME_ADD,SEZCENS,ZONASTAT,NCIRCO,SEZ_ELET,CAP,COORD_X,COORD_Y
0,POINT (1394537.871 4991843.047),EP,VIA PIETRO PALMIERI 61/A,No,No,NaN,2007,2,.,Somministrazione,...,NaN,N,NaN,760,17,3,199,10138,"1394537,871","4991843,047"
1,POINT (1394037.565 4988072.34),AE,VIA PASQUALE PAOLI 9,Si,No,NaN,2009,7,.,Acconciatori/estetisti,...,.,N,NEGOZIO,2201,56,8,799,10134,"1394037,565","4988072,34"
2,POINT (1394037.565 4988072.34),CF,VIA PASQUALE PAOLI 9,Si,No,NaN,2012,4,EXTRALIMENTARI,PICCOLE STRUTTURE,...,2,N,NEGOZIO,2201,56,8,799,10134,"1394037,565","4988072,34"
3,POINT (1393970.003 4987972.322),EP,VIA PASQUALE PAOLI 26/A,No,No,NaN,2019,5,.,Somministrazione,...,NaN,N,NaN,2200,56,8,795,10134,"1393970,003","4987972,322"
4,POINT (1393970.003 4987972.322),CF,VIA PASQUALE PAOLI 26/A,No,No,NaN,2023,11,ALIMENTARI,PICCOLE STRUTTURE,...,5,N,NaN,2200,56,8,795,10134,"1393970,003","4987972,322"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30640,POINT (1390946.163 4991676.112),CF,VIA ASIAGO 31/E,No,No,NaN,1993,12,EXTRALIMENTARI,PICCOLE STRUTTURE,...,130,N,NaN,3514,63,3,0,10142,"1390946,163","4991676,112"
30641,POINT (1396233.569 4990974.767),CF,VIA GIUSEPPE LUIGI LAGRANGE 32/M,No,No,NaN,2025,4,EXTRALIMENTARI,PICCOLE STRUTTURE,...,175,N,NaN,3136,04,1,721,10123,"1396233,569","4990974,767"
30642,POINT (1395796.956 4990710.536),CF,VIA ASSIETTA 4/A,No,No,NaN,2013,10,EXTRALIMENTARI,PICCOLE STRUTTURE,...,15,N,NaN,373,10,1,50,10128,"1395796,956","4990710,536"
30643,POINT (1395796.956 4990710.536),CF,VIA ASSIETTA 4/A,No,No,NaN,2013,10,EXTRALIMENTARI,PICCOLE STRUTTURE,...,15,N,NaN,373,10,1,50,10128,"1395796,956","4990710,536"
30644,POINT (1394083.699 4993847.926),EP,CORSO POTENZA 22,No,No,NaN,2025,11,ALTRO,Somministrazione,...,NaN,N,NaN,1245,29,4,351,10143,"1394083,699","4993847,926"

In [117]:
com.shape

(30645, 25)

In [118]:
com = com.rename(columns={
    "WKT_GEOM": "geometry_wkt",
    "C_COMP_MERC": "commercial_activity_id",
    "INDIRIZZ": "address",
    "CARRAIO": "driveway_access",
    "FRONTE": "street_front",
    "INSEGNA": "shop_sign_name",
    "ANNO_INI": "start_year",
    "MESE_INI": "start_month",
    "TIPO_MER": "business_type",
    "DESC_RIP": "category",
    "DETT_RIP": "category_detail",
    "CAT_MER": "product_category",
    "PREVALEN": "main_activity",
    "TIPO_LOC": "premises_type",
    "MQ_TOT_L": "total_premises_area_sqm",
    "MQ_TOT_V": "sales_area_sqm",
    "TIPO_ADD": "staff_type",
    "NOME_ADD": "staff_name",
    "SEZCENS": "census_section",
    "ZONASTAT": "statistical_zone",
    "NCIRCO": "district_number",
    "SEZ_ELET": "electoral_section",
    "CAP": "postal_code",
    "COORD_X": "x",
    "COORD_Y": "y"
})

In [119]:
com["statistical_zone"].value_counts().sort_index()

statistical_zone
01    1219
02      37
03     776
04     965
05     617
      ...
88       3
89     177
90     371
91      93
92      32
Name: count, Length: 93, dtype: int64

In [120]:
com["statistical_zone"].dtype

dtype('O')

In [121]:
non_numeric_zones = com[
    ~com["statistical_zone"].astype(str).str.match(r"^\d+$", na=False)
]

non_numeric_zones["statistical_zone"].value_counts()

statistical_zone
17bis    66
09bis    31
Name: count, dtype: int64

In [122]:
com.columns

Index(['geometry_wkt', 'commercial_activity_id', 'address', 'driveway_access',
       'street_front', 'shop_sign_name', 'start_year', 'start_month',
       'business_type', 'category', 'category_detail', 'product_category',
       'main_activity', 'premises_type', 'total_premises_area_sqm',
       'sales_area_sqm', 'staff_type', 'staff_name', 'census_section',
       'statistical_zone', 'district_number', 'electoral_section',
       'postal_code', 'x', 'y'],
      dtype='object')

In [123]:
com.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30645 entries, 0 to 30644
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   geometry_wkt             30645 non-null  object
 1   commercial_activity_id   30645 non-null  object
 2   address                  30645 non-null  object
 3   driveway_access          30645 non-null  object
 4   street_front             30645 non-null  object
 5   shop_sign_name           0 non-null      float64
 6   start_year               30645 non-null  int64
 7   start_month              30645 non-null  int64
 8   business_type            30645 non-null  object
 9   category                 30645 non-null  object
 10  category_detail          30645 non-null  object
 11  product_category         30645 non-null  object
 12  main_activity            21440 non-null  object
 13  premises_type            30645 non-null  int64
 14  total_premises_area_sqm  30645 non-null  object
 15  sales_area_sqm           24468 non-null  object
 16  staff_type               28143 non-null  object
 17  staff_name               16513 non-null  object
 18  census_section           30645 non-null  int64
 19  statistical_zone         30645 non-null  object
 20  district_number          30645 non-null  int64
 21  electoral_section        30645 non-null  int64
 22  postal_code              30645 non-null  int64
 23  x                        30645 non-null  object
 24  y                        30645 non-null  object
dtypes: float64(1), int64(7), object(17)
memory usage: 5.8+ MB

In [124]:

com["category_clean"] = (
    com["category"]
    .astype(str)
    .str.strip()
    .str.lower()
)


com["category_group"] = com["category_clean"]

# 3. Put all somministrazione types into one group
com.loc[
    com["category_clean"].str.contains("somministrazione", case=False, na=False),
    "category_group"
] = "somministrazione"

# 4. Check result
com["category_group"].value_counts()

category_group
piccole strutture            19191
somministrazione              6177
acconciatori/estetisti        3014
forme speciali di vendita     1197
medie strutture                711
cose antiche e usate           140
giornali                       106
produttori                      64
grandi strutture                35
attività didattiche             10
Name: count, dtype: int64

In [125]:

com["address_clean"] = (
    com["address"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(",", " ", regex=False)
    .str.replace(".", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

com["statistical_zone_clean"] = (
    com["statistical_zone"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "", regex=True)
)

In [126]:
# Convert coordinates BEFORE deduplication
com["x"] = (
    com["x"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

com["y"] = (
    com["y"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

com["x"] = pd.to_numeric(com["x"], errors="coerce")
com["y"] = pd.to_numeric(com["y"], errors="coerce")

In [127]:
som = com[com["category_group"] == "somministrazione"].copy()

dup_keys = ["address_clean", "category_group", "statistical_zone_clean", "x", "y"]

som_clean = som.drop_duplicates(
    subset=dup_keys,
    keep="first"
)

print("Before:", len(som))
print("After:", len(som_clean))
print("Removed:", len(som) - len(som_clean))

Before: 6177
After: 5735
Removed: 442

In [128]:
com["x"] = com["x"].astype(str).str.replace(",", ".").astype(float)
com["y"] = com["y"].astype(str).str.replace(",", ".").astype(float)

In [129]:
dup_keys = ["address_clean", "category_clean", "statistical_zone", "x", "y"]

som_clean = som.drop_duplicates(
    subset=dup_keys,
    keep="first"
)

print("Before:", len(som))
print("After:", len(som_clean))
print("Removed:", len(som) - len(som_clean))

Before: 6177
After: 5825
Removed: 352

In [130]:
check_after = (
    som_clean.groupby(dup_keys)
    .size()
    .reset_index(name="count")
    .query("count > 1")
)

check_after

Empty DataFrame
Columns: [address_clean, category_clean, statistical_zone, x, y, count]
Index: []

In [131]:
com.isna().sum()

geometry_wkt                   0
commercial_activity_id         0
address                        0
driveway_access                0
street_front                   0
shop_sign_name             30645
start_year                     0
start_month                    0
business_type                  0
category                       0
category_detail                0
product_category               0
main_activity               9205
premises_type                  0
total_premises_area_sqm        0
sales_area_sqm              6177
staff_type                  2502
staff_name                 14132
census_section                 0
statistical_zone               0
district_number                0
electoral_section              0
postal_code                    0
x                              0
y                              0
category_clean                 0
category_group                 0
address_clean                  0
statistical_zone_clean         0
dtype: int64

In [132]:
com["business_type"].value_counts()

business_type
EXTRALIMENTARI    13379
ALTRO              5661
MISTA              4652
             .     3540
ALIMENTARI         3413
Name: count, dtype: int64

In [133]:
com.duplicated().sum()

np.int64(21)

In [134]:
metro = pd.read_csv("data/raw/fermate_linee_metro.csv")

In [135]:
metro.shape

(19, 5)

In [136]:
metro.columns

Index(['WKT_GEOM', 'ID_FERMATA', 'FERMATA', 'COORD_X', 'COORD_Y'], dtype='object')

In [137]:
metro.rename(columns={
    "WKT_GEOM": "geometry",
    "ID_FERMATA": "station_id",
    "FERMATA": "station_name",
    "COORD_X": "x",
    "COORD_Y": "y"
}, inplace=True)

In [138]:
metro["x"] = metro["x"].str.replace(",", ".").astype(float)
metro["y"] = metro["y"].str.replace(",", ".").astype(float)

In [139]:
metro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geometry      19 non-null     object
 1   station_id    19 non-null     int64
 2   station_name  19 non-null     object
 3   x             19 non-null     float64
 4   y             19 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 892.0+ bytes

In [140]:
metro.describe()

       station_id             x             y
count   19.000000  1.900000e+01  1.900000e+01
mean    10.000000  1.394355e+06  4.990917e+06
std      5.627314  1.550873e+03  1.648614e+03
min      1.000000  1.390954e+06  4.987267e+06
25%      5.500000  1.393509e+06  4.989888e+06
50%     10.000000  1.394998e+06  4.991646e+06
75%     14.500000  1.395449e+06  4.992221e+06
max     19.000000  1.396021e+06  4.992319e+06

In [141]:
metro.duplicated().sum()

np.int64(0)

In [142]:
metro["station_name"] = metro["station_name"].str.strip().str.lower()

In [143]:
metro.isna().sum()

geometry        0
station_id      0
station_name    0
x               0
y               0
dtype: int64

In [144]:
(metro[["station_id", "x", "y"]] < 0).any()

station_id    False
x             False
y             False
dtype: bool

In [145]:
# 5. Count somministrazione stores by zone
som_zone = (
    som_clean
    .groupby("statistical_zone_clean")
    .size()
    .reset_index(name="n_somministrazione")
)
som_zone

   statistical_zone_clean  n_somministrazione
0                      01                 290
1                      02                   8
2                      03                 164
3                      04                 168
4                      05                 142
..                    ...                 ...
88                     88                   2
89                     89                  38
90                     90                  63
91                     91                  33
92                     92                   5

[93 rows x 2 columns]

In [146]:
 #Merge with population
opportunity = som_zone.merge(
    pop[["statistical_zone_clean", "neighborhood_clean", "total_population"]],
    on="statistical_zone_clean",
    how="inner"
)

print("som zones:", len(som_zone))
print("population zones:", len(pop))
print("merged zones:", len(opportunity))

som zones: 93
population zones: 23
merged zones: 23

In [147]:
#  Competition indicator
opportunity["stores_per_1000_residents"] = (
    opportunity["n_somministrazione"] / opportunity["total_population"]
) * 1000

In [148]:
som_clean["x"] = (
    som_clean["x"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

som_clean["y"] = (
    som_clean["y"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

som_clean["x"] = pd.to_numeric(som_clean["x"], errors="coerce")
som_clean["y"] = pd.to_numeric(som_clean["y"], errors="coerce")

C:\Users\reyha\AppData\Local\Temp\ipykernel_23668\2349900540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  som_clean["x"] = (
C:\Users\reyha\AppData\Local\Temp\ipykernel_23668\2349900540.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  som_clean["y"] = (
C:\Users\reyha\AppData\Local\Temp\ipykernel_23668\2349900540.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  som_clean["x"] = pd.to_numeric(som_clean["x"], errors="coerce")
C:\Users\reyha\AppData\Local\Temp\ipykernel_23668\2349900540.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  som_clean["y"] = pd.to_numeric(som_clean["y"], errors="coerce")

In [149]:
som_clean[["x", "y"]].dtypes

x    float64
y    float64
dtype: object

In [150]:
# Zone centers based on store coordinates
zone_centers = (
    som_clean
    .groupby("statistical_zone_clean")[["x", "y"]]
    .mean()
    .reset_index()
    .rename(columns={
        "x": "zone_center_x",
        "y": "zone_center_y"
    })
)

In [151]:
#  Distance to nearest metro station


def nearest_metro_distance(row, metro_df):
    distances = np.sqrt(
        (metro_df["x"] - row["zone_center_x"])**2 +
        (metro_df["y"] - row["zone_center_y"])**2
    )
    return distances.min()

zone_centers["distance_to_nearest_metro"] = zone_centers.apply(
    lambda row: nearest_metro_distance(row, metro),
    axis=1
)

In [152]:
#  Merge metro distance
opportunity = opportunity.merge(
    zone_centers[["statistical_zone_clean", "distance_to_nearest_metro"]],
    on="statistical_zone_clean",
    how="left"
)

In [153]:
#  Normalize variables
def minmax(series):
    return (series - series.min()) / (series.max() - series.min())

opportunity["normalized_population"] = minmax(opportunity["total_population"])

opportunity["normalized_competition"] = minmax(
    opportunity["stores_per_1000_residents"]
)
opportunity["normalized_distance_to_metro"] = minmax(
    opportunity["distance_to_nearest_metro"]
)

In [154]:
# Final opportunity score
opportunity["retail_opportunity_score"] = (
    0.45 * opportunity["normalized_population"]
    - 0.35 * opportunity["normalized_competition"]
    - 0.20 * opportunity["normalized_distance_to_metro"]
)

In [155]:
#  Sort final result
opportunity_sorted = opportunity.sort_values(
    "retail_opportunity_score",
    ascending=False
)

opportunity_sorted.head(10)

,statistical_zone_clean,n_somministrazione,neighborhood_clean,total_population,stores_per_1000_residents,distance_to_nearest_metro,normalized_population,normalized_competition,normalized_distance_to_metro,retail_opportunity_score
17,18,38,18 barriera di milano,50505,0.752401,471.517438,0.872367,0.072456,0.084686,0.350268
12,13,57,13 pozzo strada,55759,1.022256,1883.975066,1.000000,0.109794,0.586539,0.294264
9,10,89,10 mercati generali,47124,1.888634,423.253131,0.790234,0.229666,0.067537,0.261715
10,11,129,11 santa rita,55185,2.337592,1709.762213,0.986056,0.291784,0.524640,0.236673
14,15,20,15 le vallette,40717,0.491195,1321.497132,0.634592,0.036316,0.386688,0.195519
16,17,93,17 borgata vittoria,40500,2.296296,326.817702,0.629321,0.286070,0.033273,0.176415
5,06,160,6 san donato,49381,3.240113,1235.254089,0.845063,0.416657,0.356045,0.163239
13,14,28,14 parella,47185,0.593409,2741.687245,0.791716,0.050458,0.891289,0.160354
1,02,8,2 san salvario,34977,0.228722,1178.051525,0.495154,0.000000,0.335721,0.155675
15,16,118,16 madonna di campagna,41605,2.836198,431.448575,0.656164,0.360771,0.070449,0.154914

In [156]:
opportunity_sorted.to_csv(
    "data/processed/somministrazione_opportunity_score.csv",
    index=False
)

In [157]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (2.2.6)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\reyha\appdata\roaming\python\python311\site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\reyha\appdata\roaming\python\python311\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\reyha\appdata\local\programs\python\python311\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\reyha\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [158]:
import geopandas as gpd
import pandas as pd

In [159]:
quartieri = gpd.read_file(
    r"C:\Users\reyha\Desktop\torino-retail-intelligence\data\raw\quartieri_shapefile\ex_neighborhood_boundary.shp"
)

quartieri.head()

   ID_QUART         DENOM                                           geometry
0         1        Centro  POLYGON Z ((7.66261 45.06863 0, 7.66372 45.070...
1         2  San Salvario  POLYGON Z ((7.66699 45.04435 0, 7.66711 45.044...
2         3      Crocetta  POLYGON Z ((7.65459 45.05519 0, 7.6546 45.0554...
3         8    Vanchiglia  POLYGON Z ((7.68964 45.07477 0, 7.68993 45.074...
4         7        Aurora  POLYGON Z ((7.67133 45.08083 0, 7.67202 45.081...

In [160]:
quartieri["neighborhood_name_clean"] = (
    quartieri["DENOM"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [161]:
opportunity_sorted["neighborhood_name_clean"] = (
    opportunity_sorted["neighborhood_clean"]
    .astype(str)
    .str.lower()
    .str.replace(r"^\d+\s+", "", regex=True)
    .str.strip()
)

opportunity_sorted[["neighborhood_clean", "neighborhood_name_clean"]].head(30)

         neighborhood_clean neighborhood_name_clean
17    18 barriera di milano      barriera di milano
12          13 pozzo strada            pozzo strada
9       10 mercati generali        mercati generali
10            11 santa rita              santa rita
14           15 le vallette             le vallette
16      17 borgata vittoria        borgata vittoria
5              6 san donato              san donato
13               14 parella                 parella
1            2 san salvario            san salvario
15   16 madonna di campagna     madonna di campagna
6                  7 aurora                  aurora
11        12 mirafiori nord          mirafiori nord
4                 5 cenisia                 cenisia
7              8 vanchiglia              vanchiglia
19           20 regio parco             regio parco
22         23 mirafiori sud           mirafiori sud
3               4 san paolo               san paolo
2                3 crocetta                crocetta
18              19 falchera                falchera
0                  1 centro                  centro
20    21 madonna del pilone      madonna del pilone
8        9 nizza millefonti        nizza millefonti
21  22 borgo po e cavoretto    borgo po e cavoretto

In [162]:
opportunity_map = opportunity.copy()

opportunity_map["neighborhood_name_clean"] = (
    opportunity_map["neighborhood_clean"]
    .astype(str)
    .str.lower()
    .str.replace(r"^\d+\s+", "", regex=True)
    .str.strip()
)

In [163]:
print(quartieri.columns)
print(opportunity_map.columns)

Index(['ID_QUART', 'DENOM', 'geometry', 'neighborhood_name_clean'], dtype='object')
Index(['statistical_zone_clean', 'n_somministrazione', 'neighborhood_clean',
       'total_population', 'stores_per_1000_residents',
       'distance_to_nearest_metro', 'normalized_population',
       'normalized_competition', 'normalized_distance_to_metro',
       'retail_opportunity_score', 'neighborhood_name_clean'],
      dtype='object')

In [164]:
quartieri_score = quartieri.merge(
    opportunity_map,
    on="neighborhood_name_clean",
    how="left"
)

quartieri_score.head()

,ID_QUART,DENOM,geometry,neighborhood_name_clean,statistical_zone_clean,n_somministrazione,neighborhood_clean,total_population,stores_per_1000_residents,distance_to_nearest_metro,normalized_population,normalized_competition,normalized_distance_to_metro,retail_opportunity_score
0,1,Centro,"POLYGON Z ((7.66261 45.06863 0, 7.66372 45.070...",centro,01,290.0,1 centro,42244.0,6.864880,983.714296,0.671687,0.918180,0.266672,-0.072438
1,2,San Salvario,"POLYGON Z ((7.66699 45.04435 0, 7.66711 45.044...",san salvario,02,8.0,2 san salvario,34977.0,0.228722,1178.051525,0.495154,0.000000,0.335721,0.155675
2,3,Crocetta,"POLYGON Z ((7.65459 45.05519 0, 7.6546 45.0554...",crocetta,03,164.0,3 crocetta,34009.0,4.822253,837.251127,0.471639,0.635562,0.214633,-0.053136
3,8,Vanchiglia,"POLYGON Z ((7.68964 45.07477 0, 7.68993 45.074...",vanchiglia,08,89.0,8 vanchiglia,29935.0,2.973108,367.906077,0.372671,0.379714,0.047872,0.025228
4,7,Aurora,"POLYGON Z ((7.67133 45.08083 0, 7.67202 45.081...",aurora,07,96.0,7 aurora,39692.0,2.418623,713.509776,0.609693,0.302995,0.170667,0.134180

In [165]:
quartieri_score["retail_opportunity_score"].isna().sum()

np.int64(1)

In [166]:
quartieri_score[
    quartieri_score["retail_opportunity_score"].isna()
][[
    "ID_QUART",
    "DENOM",
    "neighborhood_name_clean"
]]

    ID_QUART       DENOM neighborhood_name_clean
15        15  Le Valette              le valette

In [167]:
print("Names in shapefile:")
print(sorted(quartieri["neighborhood_name_clean"].unique()))

print("\nNames in opportunity table:")
print(sorted(opportunity_map["neighborhood_name_clean"].unique()))

Names in shapefile:
['aurora', 'barriera di milano', 'borgata vittoria', 'borgo po e cavoretto', 'cenisia', 'centro', 'crocetta', 'falchera', 'le valette', 'madonna del pilone', 'madonna di campagna', 'mercati generali', 'mirafiori nord', 'mirafiori sud', 'nizza millefonti', 'parella', 'pozzo strada', 'regio parco', 'san donato', 'san paolo', 'san salvario', 'santa rita', 'vanchiglia']

Names in opportunity table:
['aurora', 'barriera di milano', 'borgata vittoria', 'borgo po e cavoretto', 'cenisia', 'centro', 'crocetta', 'falchera', 'le vallette', 'madonna del pilone', 'madonna di campagna', 'mercati generali', 'mirafiori nord', 'mirafiori sud', 'nizza millefonti', 'parella', 'pozzo strada', 'regio parco', 'san donato', 'san paolo', 'san salvario', 'santa rita', 'vanchiglia']

In [168]:
quartieri["neighborhood_name_clean"] = quartieri["neighborhood_name_clean"].replace({
    "le valette": "le vallette"
})

In [169]:
quartieri_score = quartieri.merge(
    opportunity_map,
    on="neighborhood_name_clean",
    how="left"
)

In [170]:
quartieri_score["retail_opportunity_score"].isna().sum()

np.int64(0)

In [171]:
quartieri_score.columns

Index(['ID_QUART', 'DENOM', 'geometry', 'neighborhood_name_clean',
       'statistical_zone_clean', 'n_somministrazione', 'neighborhood_clean',
       'total_population', 'stores_per_1000_residents',
       'distance_to_nearest_metro', 'normalized_population',
       'normalized_competition', 'normalized_distance_to_metro',
       'retail_opportunity_score'],
      dtype='object')

In [172]:
quartieri_score.to_file(
    r"C:\Users\reyha\Desktop\torino-retail-intelligence\data\processed\torino_quartieri_opportunity.geojson",
    driver="GeoJSON"
)

In [173]:
quartieri_score.to_file(
    r"C:\Users\reyha\Desktop\torino-retail-intelligence\data\processed\torino_quartieri_opportunity.geojson",
    driver="GeoJSON"
)

In [174]:
quartieri_score.drop(columns="geometry").to_csv(
    r"C:\Users\reyha\Desktop\torino-retail-intelligence\data\processed\torino_quartieri_opportunity_table.csv",
    index=False
)

In [175]:
quartieri_score.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [176]:
def opportunity_level(x):
    if x >= 0.20:
        return "Very High Opportunity"
    elif x >= 0.05:
        return "High Opportunity"
    elif x >= -0.05:
        return "Medium Opportunity"
    elif x >= -0.15:
        return "Low Opportunity"
    else:
        return "Very Low Opportunity"

quartieri_score["opportunity_level"] = quartieri_score["retail_opportunity_score"].apply(opportunity_level)

In [177]:
quartieri_score.to_crs(epsg=4326).to_file(
    "torino_quartieri_opportunity.geojson",
    driver="GeoJSON"
)

quartieri_score.drop(columns="geometry").to_csv(
    "torino_quartieri_opportunity.csv",
    index=False
)

In [178]:
# Make sure geometry is in WGS84 for Power BI
quartieri_score = quartieri_score.to_crs(epsg=4326)

# Create centroids safely using projected CRS first
centroids = quartieri_score.to_crs(epsg=32632).centroid.to_crs(epsg=4326)

quartieri_score["longitude"] = centroids.x
quartieri_score["latitude"] = centroids.y

quartieri_score.drop(columns="geometry").to_csv(
    "torino_quartieri_opportunity.csv",
    index=False
)

quartieri_score.to_file(
    "torino_quartieri_opportunity.geojson",
    driver="GeoJSON"
)

In [179]:
quartieri_score.head(10)

,ID_QUART,DENOM,geometry,neighborhood_name_clean,statistical_zone_clean,n_somministrazione,neighborhood_clean,total_population,stores_per_1000_residents,distance_to_nearest_metro,normalized_population,normalized_competition,normalized_distance_to_metro,retail_opportunity_score,opportunity_level,longitude,latitude
0,1,Centro,"POLYGON Z ((7.66261 45.06863 0, 7.66372 45.070...",centro,01,290,1 centro,42244,6.864880,983.714296,0.671687,0.918180,0.266672,-0.072438,Low Opportunity,7.680855,45.069516
1,2,San Salvario,"POLYGON Z ((7.66699 45.04435 0, 7.66711 45.044...",san salvario,02,8,2 san salvario,34977,0.228722,1178.051525,0.495154,0.000000,0.335721,0.155675,High Opportunity,7.679115,45.051296
2,3,Crocetta,"POLYGON Z ((7.65459 45.05519 0, 7.6546 45.0554...",crocetta,03,164,3 crocetta,34009,4.822253,837.251127,0.471639,0.635562,0.214633,-0.053136,Low Opportunity,7.666295,45.057796
3,8,Vanchiglia,"POLYGON Z ((7.68964 45.07477 0, 7.68993 45.074...",vanchiglia,08,89,8 vanchiglia,29935,2.973108,367.906077,0.372671,0.379714,0.047872,0.025228,Medium Opportunity,7.711068,45.075892
4,7,Aurora,"POLYGON Z ((7.67133 45.08083 0, 7.67202 45.081...",aurora,07,96,7 aurora,39692,2.418623,713.509776,0.609693,0.302995,0.170667,0.134180,High Opportunity,7.687366,45.081726
5,22,Borgo Po e Cavoretto,"POLYGON Z ((7.67391 45.01985 0, 7.67394 45.019...",borgo po e cavoretto,22,66,22 borgo po e cavoretto,19947,3.308768,3047.653812,0.130038,0.426156,1.000000,-0.290638,Very Low Opportunity,7.701352,45.041642
6,21,Madonna del Pilone,"POLYGON Z ((7.70845 45.06838 0, 7.70869 45.067...",madonna del pilone,21,24,21 madonna del pilone,14594,1.644511,2040.377948,0.000000,0.195889,0.642110,-0.196983,Very Low Opportunity,7.739449,45.067527
7,6,San Donato,"POLYGON Z ((7.64357 45.07593 0, 7.64371 45.076...",san donato,06,160,6 san donato,49381,3.240113,1235.254089,0.845063,0.416657,0.356045,0.163239,High Opportunity,7.660213,45.083277
8,5,Cenisia,"POLYGON Z ((7.6386 45.06915 0, 7.6389 45.06955...",cenisia,05,142,5 cenisia,36856,3.852833,399.725361,0.540799,0.501433,0.059178,0.056023,High Opportunity,7.653431,45.070381
9,16,Madonna di Campagna,"POLYGON Z ((7.64517 45.10665 0, 7.64517 45.107...",madonna di campagna,16,118,16 madonna di campagna,41605,2.836198,431.448575,0.656164,0.360771,0.070449,0.154914,High Opportunity,7.663887,45.115248

In [180]:
#This creates a folder for PostgreSQL file
from pathlib import Path

output_dir = Path("data/processed/postgresql")
output_dir.mkdir(parents=True, exist_ok=True)

In [181]:
dim_quartiere = pop[[
    "neighborhood",
    "neighborhood_clean",
    "statistical_zone_clean"
]].copy()

# One row per statistical zone / quartiere
dim_quartiere = dim_quartiere.drop_duplicates(
    subset=["statistical_zone_clean"]
).reset_index(drop=True)

# Rename columns
dim_quartiere = dim_quartiere.rename(columns={
    "neighborhood": "quartiere_name",
    "neighborhood_clean": "quartiere_name_clean"
})

# Create artificial numeric ID
dim_quartiere.insert(
    0,
    "quartiere_id",
    range(1, len(dim_quartiere) + 1)
)

# Reorder columns
dim_quartiere = dim_quartiere[[
    "quartiere_id",
    "quartiere_name",
    "quartiere_name_clean",
    "statistical_zone_clean"
]]

# Save CSV
dim_quartiere.to_csv("dim_quartiere.csv", index=False)

dim_quartiere.head(10)

,quartiere_id,quartiere_name,quartiere_name_clean,statistical_zone_clean
0,1,1 Centro,1 centro,01
1,2,2 San Salvario,2 san salvario,02
2,3,3 Crocetta,3 crocetta,03
3,4,4 San Paolo,4 san paolo,04
4,5,5 Cenisia,5 cenisia,05
5,6,6 San Donato,6 san donato,06
6,7,7 Aurora,7 aurora,07
7,8,8 Vanchiglia,8 vanchiglia,08
8,9,9 Nizza millefonti,9 nizza millefonti,09
9,10,10 Mercati generali,10 mercati generali,10

In [182]:
print(dim_quartiere.columns)

Index(['quartiere_id', 'quartiere_name', 'quartiere_name_clean',
       'statistical_zone_clean'],
      dtype='object')

In [183]:
dim_quartiere.shape

(23, 4)

In [184]:
fact_population = pop[[
    "statistical_zone_clean",
    "total_population",
    "male",
    "female"
]].copy()

fact_population["quartiere_id"] = fact_population["statistical_zone_clean"].astype(int)

fact_population["year"] = 2023  # change if your population data is from another year

fact_population = fact_population.rename(columns={
    "total_population": "total_residents",
    "male": "male_residents",
    "female": "female_residents"
})

fact_population = fact_population[[
    "quartiere_id",
    "year",
    "total_residents",
    "male_residents",
    "female_residents"
]]

fact_population.insert(
    0,
    "population_id",
    range(1, len(fact_population) + 1)
)

fact_population.to_csv("fact_population.csv", index=False)

fact_population.head()

,population_id,quartiere_id,year,total_residents,male_residents,female_residents
0,1,1,2023,42244,21404,20840
1,2,2,2023,34977,16551,18426
2,3,3,2023,34009,15675,18334
3,4,4,2023,33352,15847,17505
4,5,5,2023,36856,17477,19379

In [185]:
fact_population.shape

(23, 6)

In [186]:
fact_population["quartiere_id"].isna().sum()

np.int64(0)

In [187]:
som_clean.columns

Index(['geometry_wkt', 'commercial_activity_id', 'address', 'driveway_access',
       'street_front', 'shop_sign_name', 'start_year', 'start_month',
       'business_type', 'category', 'category_detail', 'product_category',
       'main_activity', 'premises_type', 'total_premises_area_sqm',
       'sales_area_sqm', 'staff_type', 'staff_name', 'census_section',
       'statistical_zone', 'district_number', 'electoral_section',
       'postal_code', 'x', 'y', 'category_clean', 'category_group',
       'address_clean', 'statistical_zone_clean'],
      dtype='object')

In [188]:
som_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5825 entries, 0 to 30644
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   geometry_wkt             5825 non-null   object
 1   commercial_activity_id   5825 non-null   object
 2   address                  5825 non-null   object
 3   driveway_access          5825 non-null   object
 4   street_front             5825 non-null   object
 5   shop_sign_name           0 non-null      float64
 6   start_year               5825 non-null   int64
 7   start_month              5825 non-null   int64
 8   business_type            5825 non-null   object
 9   category                 5825 non-null   object
 10  category_detail          5825 non-null   object
 11  product_category         5825 non-null   object
 12  main_activity            0 non-null      object
 13  premises_type            5825 non-null   int64
 14  total_premises_area_sqm  5825 non-null   object
 15  sales_area_sqm           0 non-null      object
 16  staff_type               5561 non-null   object
 17  staff_name               88 non-null     object
 18  census_section           5825 non-null   int64
 19  statistical_zone         5825 non-null   object
 20  district_number          5825 non-null   int64
 21  electoral_section        5825 non-null   int64
 22  postal_code              5825 non-null   int64
 23  x                        5825 non-null   float64
 24  y                        5825 non-null   float64
 25  category_clean           5825 non-null   object
 26  category_group           5825 non-null   object
 27  address_clean            5825 non-null   object
 28  statistical_zone_clean   5825 non-null   object
dtypes: float64(3), int64(7), object(19)
memory usage: 1.3+ MB

In [189]:
fact_commercial_activity = som_clean.copy()

# Add quartiere_id from dim_quartiere using statistical_zone_clean
fact_commercial_activity = fact_commercial_activity.merge(
    dim_quartiere[["quartiere_id", "statistical_zone_clean"]],
    on="statistical_zone_clean",
    how="left"
)

# Check missing IDs
print(fact_commercial_activity["quartiere_id"].isna().sum())

3402

In [191]:
fact_commercial_activity = som_clean.copy()

# Bring quartiere_id from dim_quartiere
fact_commercial_activity = fact_commercial_activity.merge(
    dim_quartiere[["quartiere_id", "statistical_zone_clean"]],
    on="statistical_zone_clean",
    how="left"
)

# Check that all activities found a quartiere_id
print("Missing quartiere_id:", fact_commercial_activity["quartiere_id"].isna().sum())

# store name
fact_commercial_activity["store_name"] = fact_commercial_activity["shop_sign_name"]

fact_commercial_activity = fact_commercial_activity.rename(columns={
    "commercial_activity_id": "source_commercial_activity_id",
    "category": "category_name",
    "x": "x_coord",
    "y": "y_coord"
})

fact_commercial_activity = fact_commercial_activity[[
    "source_commercial_activity_id",
    "store_name",
    "category_name",
    "category_group",
    "quartiere_id",
    "x_coord",
    "y_coord",
    "address"
]]

fact_commercial_activity.insert(
    0,
    "activity_id",
    range(1, len(fact_commercial_activity) + 1)
)

fact_commercial_activity.to_csv("fact_commercial_activity.csv", index=False)

fact_commercial_activity.head()

Missing quartiere_id: 3402

,activity_id,source_commercial_activity_id,store_name,category_name,category_group,quartiere_id,x_coord,y_coord,address
0,1,EP,NaN,Somministrazione,somministrazione,17.0,1394537.871,4991843.047,VIA PIETRO PALMIERI 61/A
1,2,EP,NaN,Somministrazione,somministrazione,NaN,1393970.003,4987972.322,VIA PASQUALE PAOLI 26/A
2,3,EP,NaN,Somministrazione,somministrazione,NaN,1392773.455,4994671.188,VIA PIANEZZA 212/F
3,4,EP,NaN,Somministrazione,somministrazione,NaN,1394041.603,4990876.168,CORSO PESCHIERA 138 bis/D
4,5,EP,NaN,Somministrazione,somministrazione,NaN,1393966.780,4990868.407,CORSO PESCHIERA 145/A

In [192]:
print("dim_quartiere zones:")
print(sorted(dim_quartiere["statistical_zone_clean"].astype(str).unique()))

dim_quartiere zones:
['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']

In [193]:
print("som_clean zones:")
print(sorted(som_clean["statistical_zone_clean"].astype(str).unique()))

som_clean zones:
['01', '02', '03', '04', '05', '06', '07', '08', '09', '09bis', '10', '11', '12', '13', '14', '15', '16', '17', '17bis', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92']

In [194]:
print("Zones in som_clean but not in dim_quartiere:")
print(sorted(
    set(som_clean["statistical_zone_clean"].astype(str).unique()) -
    set(dim_quartiere["statistical_zone_clean"].astype(str).unique())
))

Zones in som_clean but not in dim_quartiere:
['09bis', '17bis', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92']

In [195]:
print("Number of shops in unmatched zones:")
unmatched_zones = (
    set(som_clean["statistical_zone_clean"].astype(str).unique()) -
    set(dim_quartiere["statistical_zone_clean"].astype(str).unique())
)

print(
    som_clean[som_clean["statistical_zone_clean"].astype(str).isin(unmatched_zones)]
    ["statistical_zone_clean"]
    .value_counts()
    .sort_index()
)

Number of shops in unmatched zones:
statistical_zone_clean
09bis     19
17bis     20
24       118
25        66
26        87
        ...
88         2
89        38
90        63
91        33
92         5
Name: count, Length: 70, dtype: int64

In [196]:
print(quartieri.crs)
print(quartieri[["ID_QUART", "DENOM"]].head())

EPSG:4326
   ID_QUART         DENOM
0         1        Centro
1         2  San Salvario
2         3      Crocetta
3         8    Vanchiglia
4         7        Aurora

In [197]:
print("Quartieri bounds:")
print(quartieri.total_bounds)

print("\nShop x range:")
print(som_clean["x"].min(), som_clean["x"].max())

print("\nShop y range:")
print(som_clean["y"].min(), som_clean["y"].max())

Quartieri bounds:
[ 7.57783087 45.00682796  7.77335111 45.14024403]

Shop x range:
1388982.58023302 1403309.456

Shop y range:
4984746.131 4998768.41

In [198]:
som_gdf = gpd.GeoDataFrame(
    som_clean.copy(),
    geometry=gpd.points_from_xy(som_clean["x"], som_clean["y"]),
    crs="EPSG:3003"
)

# Convert shops to the same CRS as quartieri: EPSG:4326
som_gdf = som_gdf.to_crs(quartieri.crs)

som_gdf.geometry.head()

0      POINT (7.6599 45.07201)
3     POINT (7.65351 45.03709)
5      POINT (7.63689 45.0972)
11    POINT (7.65381 45.06323)
16    POINT (7.65286 45.06315)
Name: geometry, dtype: geometry

In [199]:
som_with_quartiere = gpd.sjoin(
    som_gdf,
    quartieri[["ID_QUART", "DENOM", "geometry"]],
    how="left",
    predicate="within"
)

print("Missing quartiere after spatial join:",
      som_with_quartiere["ID_QUART"].isna().sum())

Missing quartiere after spatial join: 0

In [200]:
som_gdf.geometry.head()

0      POINT (7.6599 45.07201)
3     POINT (7.65351 45.03709)
5      POINT (7.63689 45.0972)
11    POINT (7.65381 45.06323)
16    POINT (7.65286 45.06315)
Name: geometry, dtype: geometry

In [201]:
som_with_quartiere["ID_QUART"].isna().sum()

np.int64(0)

In [202]:
dim_quartiere = quartieri[[
    "ID_QUART",
    "DENOM"
]].copy()

dim_quartiere = dim_quartiere.rename(columns={
    "ID_QUART": "quartiere_id",
    "DENOM": "quartiere_name"
})

dim_quartiere["quartiere_name_clean"] = (
    dim_quartiere["quartiere_name"]
    .astype(str)
    .str.lower()
    .str.strip()
)

dim_quartiere = dim_quartiere[[
    "quartiere_id",
    "quartiere_name",
    "quartiere_name_clean"
]]

dim_quartiere.to_csv("dim_quartiere.csv", index=False)

dim_quartiere.head()

   quartiere_id quartiere_name quartiere_name_clean
0             1         Centro               centro
1             2   San Salvario         san salvario
2             3       Crocetta             crocetta
3             8     Vanchiglia           vanchiglia
4             7         Aurora               aurora

In [203]:
fact_commercial_activity = som_with_quartiere.copy()

# shop_sign_name is completely empty in your data
fact_commercial_activity["store_name"] = None

fact_commercial_activity = fact_commercial_activity.rename(columns={
    "commercial_activity_id": "source_commercial_activity_id",
    "category": "category_name",
    "ID_QUART": "quartiere_id",
    "x": "x_coord",
    "y": "y_coord"
})

fact_commercial_activity = fact_commercial_activity[[
    "source_commercial_activity_id",
    "store_name",
    "category_name",
    "category_group",
    "quartiere_id",
    "x_coord",
    "y_coord",
    "address"
]]

fact_commercial_activity.insert(
    0,
    "activity_id",
    range(1, len(fact_commercial_activity) + 1)
)

fact_commercial_activity.to_csv("fact_commercial_activity.csv", index=False)

fact_commercial_activity.head()

,activity_id,source_commercial_activity_id,store_name,category_name,category_group,quartiere_id,x_coord,y_coord,address
0,1,EP,None,Somministrazione,somministrazione,5,1394537.871,4991843.047,VIA PIETRO PALMIERI 61/A
3,2,EP,None,Somministrazione,somministrazione,10,1393970.003,4987972.322,VIA PASQUALE PAOLI 26/A
5,3,EP,None,Somministrazione,somministrazione,15,1392773.455,4994671.188,VIA PIANEZZA 212/F
11,4,EP,None,Somministrazione,somministrazione,5,1394041.603,4990876.168,CORSO PESCHIERA 138 bis/D
16,5,EP,None,Somministrazione,somministrazione,4,1393966.780,4990868.407,CORSO PESCHIERA 145/A

In [204]:
fact_commercial_activity["quartiere_id"].isna().sum()

np.int64(0)

In [244]:
som_quartiere = (
    som_with_quartiere
    .groupby(["ID_QUART", "DENOM"])
    .size()
    .reset_index(name="n_somministrazione")
    .rename(columns={
        "ID_QUART": "quartiere_id",
        "DENOM": "quartiere_name"
    })
)

som_quartiere.sort_values(
    "n_somministrazione",
    ascending=False
)

    quartiere_id        quartiere_name  n_somministrazione
0              1                Centro                1117
1              2          San Salvario                 445
6              7                Aurora                 337
4              5               Cenisia                 293
5              6            San Donato                 273
17            18    Barriera di Milano                 269
10            11            Santa Rita                 263
2              3              Crocetta                 259
12            13          Pozzo Strada                 244
7              8            Vanchiglia                 225
9             10      Mercati generali                 212
8              9      Nizza millefonti                 203
3              4             San Paolo                 188
15            16   Madonna di Campagna                 185
13            14               Parella                 182
16            17      Borgata Vittoria                 174
21            22  Borgo Po e Cavoretto                 169
19            20           Regio Parco                 151
22            23         Mirafiori Sud                 147
14            15            Le Valette                 146
11            12        Mirafiori Nord                 138
18            19              Falchera                 113
20            21    Madonna del Pilone                  92

In [245]:
som_quartiere.shape

(23, 3)

In [246]:
dim_quartiere
fact_commercial_activity
som_quartiere.sort_values("n_somministrazione", ascending=False)

    quartiere_id        quartiere_name  n_somministrazione
0              1                Centro                1117
1              2          San Salvario                 445
6              7                Aurora                 337
4              5               Cenisia                 293
5              6            San Donato                 273
17            18    Barriera di Milano                 269
10            11            Santa Rita                 263
2              3              Crocetta                 259
12            13          Pozzo Strada                 244
7              8            Vanchiglia                 225
9             10      Mercati generali                 212
8              9      Nizza millefonti                 203
3              4             San Paolo                 188
15            16   Madonna di Campagna                 185
13            14               Parella                 182
16            17      Borgata Vittoria                 174
21            22  Borgo Po e Cavoretto                 169
19            20           Regio Parco                 151
22            23         Mirafiori Sud                 147
14            15            Le Valette                 146
11            12        Mirafiori Nord                 138
18            19              Falchera                 113
20            21    Madonna del Pilone                  92

In [207]:
print("Names in pop but not in dim_quartiere:")
print(
    sorted(
        set(pop["neighborhood_clean"]) -
        set(dim_quartiere["quartiere_name_clean"])
    )
)

print("\nNames in dim_quartiere but not in pop:")
print(
    sorted(
        set(dim_quartiere["quartiere_name_clean"]) -
        set(pop["neighborhood_clean"])
    )
)

Names in pop but not in dim_quartiere:
['1 centro', '10 mercati generali', '11 santa rita', '12 mirafiori nord', '13 pozzo strada', '14 parella', '15 le vallette', '16 madonna di campagna', '17 borgata vittoria', '18 barriera di milano', '19 falchera', '2 san salvario', '20 regio parco', '21 madonna del pilone', '22 borgo po e cavoretto', '23 mirafiori sud', '3 crocetta', '4 san paolo', '5 cenisia', '6 san donato', '7 aurora', '8 vanchiglia', '9 nizza millefonti']

Names in dim_quartiere but not in pop:
['aurora', 'barriera di milano', 'borgata vittoria', 'borgo po e cavoretto', 'cenisia', 'centro', 'crocetta', 'falchera', 'le valette', 'madonna del pilone', 'madonna di campagna', 'mercati generali', 'mirafiori nord', 'mirafiori sud', 'nizza millefonti', 'parella', 'pozzo strada', 'regio parco', 'san donato', 'san paolo', 'san salvario', 'santa rita', 'vanchiglia']

In [208]:
pop["quartiere_name_clean"] = (
    pop["neighborhood_clean"]
    .str.replace(r"^\d+\s*", "", regex=True)   # remove starting number
    .str.strip()
)

# Fix the only spelling mismatch
pop["quartiere_name_clean"] = pop["quartiere_name_clean"].replace({
    "le vallette": "le valette"
})

In [209]:
pop[[
    "neighborhood_clean",
    "quartiere_name_clean"
]].head(10)

    neighborhood_clean quartiere_name_clean
0             1 centro               centro
1       2 san salvario         san salvario
2           3 crocetta             crocetta
3          4 san paolo            san paolo
4            5 cenisia              cenisia
5         6 san donato           san donato
6             7 aurora               aurora
7         8 vanchiglia           vanchiglia
8   9 nizza millefonti     nizza millefonti
9  10 mercati generali     mercati generali

In [210]:
print("Names in pop but not in dim_quartiere:")
print(
    sorted(
        set(pop["quartiere_name_clean"]) -
        set(dim_quartiere["quartiere_name_clean"])
    )
)

print("\nNames in dim_quartiere but not in pop:")
print(
    sorted(
        set(dim_quartiere["quartiere_name_clean"]) -
        set(pop["quartiere_name_clean"])
    )
)

Names in pop but not in dim_quartiere:
[]

Names in dim_quartiere but not in pop:
[]

In [211]:
fact_population = pop[[
    "quartiere_name_clean",
    "total_population",
    "male",
    "female"
]].copy()

fact_population = fact_population.merge(
    dim_quartiere[["quartiere_id", "quartiere_name_clean"]],
    on="quartiere_name_clean",
    how="left"
)

print("Missing quartiere_id:", fact_population["quartiere_id"].isna().sum())

Missing quartiere_id: 0

In [247]:
fact_population["year"] = 2023

fact_population = fact_population.rename(columns={
    "total_population": "total_residents",
    "male": "male_residents",
    "female": "female_residents"
})

fact_population = fact_population[[
    "quartiere_id",
    "year",
    "total_residents",
    "male_residents",
    "female_residents"
]]

fact_population.insert(
    0,
    "population_id",
    range(1, len(fact_population) + 1)
)

fact_population.to_csv("fact_population.csv", index=False)

fact_population

,population_id,quartiere_id,year,total_residents,male_residents,female_residents
0,1,1,2023,42244,21404,20840
1,2,2,2023,34977,16551,18426
2,3,3,2023,34009,15675,18334
3,4,4,2023,33352,15847,17505
4,5,5,2023,36856,17477,19379
5,6,6,2023,49381,23472,25909
6,7,7,2023,39692,19691,20001
7,8,8,2023,29935,13770,16165
8,9,9,2023,27762,13100,14662
9,10,10,2023,47124,22238,24886
10,11,11,2023,55185,25505,29680
11,12,12,2023,42030,19751,22279
12,13,13,2023,55759,26078,29681
13,14,14,2023,47185,22270,24915
14,15,15,2023,40717,19658,21059
15,16,16,2023,41605,20243,21362
16,17,17,2023,40500,19414,21086
17,18,18,2023,50505,25221,25284
18,19,19,2023,25970,12609,13361
19,20,20,2023,28799,13757,15042
20,21,21,2023,14594,6858,7736
21,22,22,2023,19947,9239,10708
22,23,23,2023,34188,16378,17810

In [248]:
fact_population.shape

(23, 6)

In [214]:
# Convert quartieri polygons to projected CRS for distance calculation in meters
quartieri_3003 = quartieri.to_crs("EPSG:3003").copy()

# Calculate centroid of each quartiere
quartieri_3003["centroid"] = quartieri_3003.geometry.centroid

In [215]:
quartieri_3003["centroid_x"] = quartieri_3003["centroid"].x
quartieri_3003["centroid_y"] = quartieri_3003["centroid"].y

In [217]:
import numpy as np

def nearest_metro_distance(row, metro_df):
    distances = np.sqrt(
        (metro_df["x"] - row["centroid_x"])**2 +
        (metro_df["y"] - row["centroid_y"])**2
    )
    return distances.min()

quartieri_3003["distance_to_nearest_metro"] = quartieri_3003.apply(
    lambda row: nearest_metro_distance(row, metro),
    axis=1
)

In [218]:
quartiere_metro_distance = quartieri_3003[[
    "ID_QUART",
    "distance_to_nearest_metro"
]].copy()

quartiere_metro_distance = quartiere_metro_distance.rename(columns={
    "ID_QUART": "quartiere_id"
})

In [219]:
retail_score = dim_quartiere[[
    "quartiere_id",
    "quartiere_name"
]].copy()

In [220]:
retail_score = retail_score.merge(
    som_quartiere[[
        "quartiere_id",
        "n_somministrazione"
    ]],
    on="quartiere_id",
    how="left"
)

retail_score["n_somministrazione"] = (
    retail_score["n_somministrazione"]
    .fillna(0)
    .astype(int)
)

In [221]:
retail_score = retail_score.merge(
    quartiere_metro_distance,
    on="quartiere_id",
    how="left"
)

In [222]:
retail_score.head()

   quartiere_id quartiere_name  n_somministrazione  distance_to_nearest_metro
0             1         Centro                1117                 767.239399
1             2   San Salvario                 445                 344.153132
2             3       Crocetta                 259                 846.284614
3             8     Vanchiglia                 225                2920.631752
4             7         Aurora                 337                1727.781043

In [224]:
retail_score.columns

Index(['quartiere_id', 'quartiere_name', 'n_somministrazione',
       'distance_to_nearest_metro'],
      dtype='object')

In [225]:
fact_population.columns

Index(['population_id', 'quartiere_id', 'year', 'total_residents',
       'male_residents', 'female_residents'],
      dtype='object')

In [226]:
retail_score = retail_score.merge(
    fact_population[[
        "quartiere_id",
        "total_residents"
    ]],
    on="quartiere_id",
    how="left"
)

retail_score = retail_score.rename(columns={
    "total_residents": "total_population"
})

retail_score.head()

,quartiere_id,quartiere_name,n_somministrazione,distance_to_nearest_metro,total_population
0,1,Centro,1117,767.239399,42244
1,2,San Salvario,445,344.153132,34977
2,3,Crocetta,259,846.284614,34009
3,8,Vanchiglia,225,2920.631752,29935
4,7,Aurora,337,1727.781043,39692

In [227]:
retail_score["stores_per_1000_residents"] = (
    retail_score["n_somministrazione"] /
    retail_score["total_population"]
) * 1000

In [228]:
retail_score["competition_index"] = retail_score["stores_per_1000_residents"]

In [229]:
retail_score["competition_index"] = retail_score["stores_per_1000_residents"]

In [230]:
def minmax(series):
    return (series - series.min()) / (series.max() - series.min())

In [232]:
# 4. create normalized columns
retail_score["normalized_population"] = minmax(
    retail_score["total_population"]
)

retail_score["normalized_competition"] = minmax(
    retail_score["competition_index"]
)

retail_score["normalized_distance_to_metro"] = minmax(
    retail_score["distance_to_nearest_metro"]
)

In [233]:
retail_score["retail_opportunity_score"] = (
    0.45 * retail_score["normalized_population"]
    - 0.35 * retail_score["normalized_competition"]
    - 0.20 * retail_score["normalized_distance_to_metro"]
)

In [234]:
retail_score.columns

Index(['quartiere_id', 'quartiere_name', 'n_somministrazione',
       'distance_to_nearest_metro', 'total_population',
       'stores_per_1000_residents', 'competition_index',
       'normalized_population', 'normalized_competition',
       'normalized_distance_to_metro', 'retail_opportunity_score'],
      dtype='object')

In [235]:
retail_score["retail_opportunity_score"] = (
    0.45 * retail_score["normalized_population"]
    - 0.35 * retail_score["normalized_competition"]
    - 0.20 * retail_score["normalized_distance_to_metro"]
)

In [236]:
def opportunity_level(x):
    if x >= 0.20:
        return "Very High Opportunity"
    elif x >= 0.05:
        return "High Opportunity"
    elif x >= -0.05:
        return "Medium Opportunity"
    elif x >= -0.15:
        return "Low Opportunity"
    else:
        return "Very Low Opportunity"

retail_score["opportunity_level"] = retail_score[
    "retail_opportunity_score"
].apply(opportunity_level)

In [237]:
retail_score.sort_values(
    "retail_opportunity_score",
    ascending=False
)[[
    "quartiere_name",
    "n_somministrazione",
    "total_population",
    "stores_per_1000_residents",
    "distance_to_nearest_metro",
    "retail_opportunity_score",
    "opportunity_level"
]]

,quartiere_name,n_somministrazione,total_population,stores_per_1000_residents,distance_to_nearest_metro,retail_opportunity_score,opportunity_level
11,Pozzo Strada,244,55759,4.375975,880.586222,0.408269,Very High Opportunity
20,Santa Rita,263,55185,4.765788,1990.078154,0.356939,Very High Opportunity
18,Parella,182,47185,3.857158,844.653445,0.323651,Very High Opportunity
7,San Donato,273,49381,5.528442,825.898299,0.323060,Very High Opportunity
17,Mercati generali,212,47124,4.498769,1135.411657,0.303024,Very High Opportunity
12,Barriera di Milano,269,50505,5.326205,2849.211228,0.266983,Very High Opportunity
22,Mirafiori Nord,138,42030,3.283369,3325.100099,0.188413,High Opportunity
15,Le Valette,146,40717,3.585726,2835.782121,0.186763,High Opportunity
8,Cenisia,293,36856,7.949859,642.400028,0.156023,High Opportunity
10,Borgata Vittoria,174,40500,4.296296,3444.099390,0.152178,High Opportunity
4,Aurora,337,39692,8.490376,1727.781043,0.140543,High Opportunity
9,Madonna di Campagna,185,41605,4.446581,4322.467194,0.130981,High Opportunity
2,Crocetta,259,34009,7.615631,846.284614,0.122755,High Opportunity
19,San Paolo,188,33352,5.636843,1769.855382,0.112878,High Opportunity
21,Nizza millefonti,203,27762,7.312153,166.172817,0.083059,High Opportunity
1,San Salvario,445,34977,12.722646,344.153132,0.073877,High Opportunity
16,Mirafiori Sud,147,34188,4.299754,3832.514140,0.069415,High Opportunity
3,Vanchiglia,225,29935,7.516285,2920.631752,0.006499,Medium Opportunity
13,Regio Parco,151,28799,5.243238,5525.526018,-0.063516,Low Opportunity
0,Centro,1117,42244,26.441625,767.239399,-0.068958,Low Opportunity
14,Falchera,113,25970,4.351174,5832.060673,-0.091780,Low Opportunity
5,Borgo Po e Cavoretto,169,19947,8.472452,2317.201028,-0.095837,Low Opportunity
6,Madonna del Pilone,92,14594,6.303961,4792.592563,-0.208959,Very Low Opportunity

In [238]:
fact_retail_score = retail_score.copy()

fact_retail_score = fact_retail_score.rename(columns={
    "n_somministrazione": "total_somministrazione"
})

fact_retail_score = fact_retail_score[[
    "quartiere_id",
    "total_somministrazione",
    "total_population",
    "stores_per_1000_residents",
    "distance_to_nearest_metro",
    "competition_index",
    "normalized_population",
    "normalized_competition",
    "normalized_distance_to_metro",
    "retail_opportunity_score",
    "opportunity_level"
]]

fact_retail_score.insert(
    0,
    "score_id",
    range(1, len(fact_retail_score) + 1)
)

fact_retail_score.to_csv("fact_retail_score.csv", index=False)

fact_retail_score.head()

,score_id,quartiere_id,total_somministrazione,total_population,stores_per_1000_residents,distance_to_nearest_metro,competition_index,normalized_population,normalized_competition,normalized_distance_to_metro,retail_opportunity_score,opportunity_level
0,1,1,1117,42244,26.441625,767.239399,26.441625,0.671687,1.000000,0.106085,-0.068958,Low Opportunity
1,2,2,445,34977,12.722646,344.153132,12.722646,0.495154,0.407599,0.031413,0.073877,High Opportunity
2,3,3,259,34009,7.615631,846.284614,7.615631,0.471639,0.187072,0.120036,0.122755,High Opportunity
3,4,8,225,29935,7.516285,2920.631752,7.516285,0.372671,0.182782,0.486148,0.006499,Medium Opportunity
4,5,7,337,39692,8.490376,1727.781043,8.490376,0.609693,0.224845,0.275616,0.140543,High Opportunity

In [240]:
print("dim_quartiere:", dim_quartiere.shape)
print("fact_population:", fact_population.shape)
print("fact_commercial_activity:", fact_commercial_activity.shape)
print("fact_retail_score:", fact_retail_score.shape)

dim_quartiere: (23, 3)
fact_population: (23, 6)
fact_commercial_activity: (5825, 9)
fact_retail_score: (23, 12)

In [239]:
fact_retail_score.isna().sum()

score_id                        0
quartiere_id                    0
total_somministrazione          0
total_population                0
stores_per_1000_residents       0
distance_to_nearest_metro       0
competition_index               0
normalized_population           0
normalized_competition          0
normalized_distance_to_metro    0
retail_opportunity_score        0
opportunity_level               0
dtype: int64